spring.application.name=taskmanager

 # Puerto en el que corre el backend
server.port=8080

# Configuracion base de datos Postgres
spring.datasource.url=jdbc:postgresql://localhost:5432/taskmanager
spring.datasource.username=luciano
spring.datasource.password=admin

# Configuración de Hibernate (JPA)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


# Loggers SpringBoot
logging.level.org.springframework.security=DEBUG

# Secret Key
jwt.secret=zS7mPAQz6d8nEV0LuR3Tx9yWpK4fGB1h




